title:             Tahir Waseer
email:             tahirwaseer@gmail.com
description:       deep learning, deep re-inforcement learning, web developer
author:            Tahir Waseer
baseurl:           ""
url:               "https://tahirwaseer.github.io"

# Social Profiles
twitter_username:  tahirwaseer
github_username:   tahirwaseer
# facebook_username: tahir.waseer

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
